# Avium Flags
AVIUM_BUILDTYPE := Release
AVIUM_VERSION_APPEND_TIME_OF_DAY := false
AVIUM_IS_OFFICIAL := true
AVIUM_MAINTAINER := Zarathos30

# Settings
AVIUM_SETTINGS_SOC_MODEL_NAME := SM8735
AVIUM_SETTINGS_DEVICE_CODENAME := onyx

# GMS
WITH_GMS := true

# Google IME
TARGET_INCLUDE_GOOGLEIME := true
TARGET_GOOGLEIME_OVERRIDE_IME := true

# Spoof Props
AVIUM_FORCE_SET_FAKE_PROP := false
